const baseOpportunities = [
  {
    id: "gs-001",
    name: "Aurora STEM Scholars",
    deadline: "2026-03-14",
    region: "North America",
    type: "STEM Scholarship",
    stage: "Drafting",
    owner: "Mila",
    funding: 45000,
    fit: 5,
    focus: "Women in engineering + mentorship requirement",
    link: "https://example.org/aurora",
  },
  {
    id: "gs-002",
    name: "Global Creative Futures",
    deadline: "2026-02-28",
    region: "Global",
    type: "Arts & Design",
    stage: "Ready",
    owner: "Kofi",
    funding: 30000,
    fit: 4,
    focus: "Portfolio-based review, requires community impact plan",
    link: "https://example.org/creative",
  },
  {
    id: "gs-003",
    name: "NextGen Public Service Fellowship",
    deadline: "2026-04-05",
    region: "US",
    type: "Public Service",
    stage: "Discovery",
    owner: "Shreya",
    funding: 25000,
    fit: 3,
    focus: "Policy internships, leadership narrative required",
    link: "https://example.org/public",
  },
  {
    id: "gs-004",
    name: "BrightPath Community College Fund",
    deadline: "2026-03-01",
    region: "US",
    type: "Access Scholarship",
    stage: "Drafting",
    owner: "Luis",
    funding: 15000,
    fit: 4,
    focus: "Community college transfer pipeline",
    link: "https://example.org/brightpath",
  },
  {
    id: "gs-005",
    name: "EcoFrontier Climate Innovators",
    deadline: "2026-05-12",
    region: "Global",
    type: "Climate & Sustainability",
    stage: "Watchlist",
    owner: "Ava",
    funding: 60000,
    fit: 5,
    focus: "Climate innovation, requires team project evidence",
    link: "https://example.org/ecofrontier",
  },
  {
    id: "gs-006",
    name: "Catalyst Health Leaders",
    deadline: "2026-02-21",
    region: "US",
    type: "Health",
    stage: "Ready",
    owner: "Maya",
    funding: 20000,
    fit: 4,
    focus: "Community health leadership program with site visits",
    link: "https://example.org/catalyst",
  },
  {
    id: "gs-007",
    name: "Blue Meridian Tech Equity",
    deadline: "2026-03-22",
    region: "North America",
    type: "Tech Equity",
    stage: "Drafting",
    owner: "Noah",
    funding: 50000,
    fit: 4,
    focus: "Tech access and equity, mentorship requirement",
    link: "https://example.org/meridian",
  },
  {
    id: "gs-008",
    name: "Lighthouse First-Gen Network",
    deadline: "2026-02-18",
    region: "US",
    type: "First-Gen",
    stage: "Ready",
    owner: "Zara",
    funding: 18000,
    fit: 5,
    focus: "First-gen support, requires cohort narrative",
    link: "https://example.org/lighthouse",
  },
  {
    id: "gs-009",
    name: "Equinox Global Scholars",
    deadline: "2026-06-10",
    region: "Global",
    type: "International Study",
    stage: "Discovery",
    owner: "Ravi",
    funding: 75000,
    fit: 3,
    focus: "Study abroad + service requirement",
    link: "https://example.org/equinox",
  },
  {
    id: "gs-010",
    name: "Momentum Rural Access",
    deadline: "2026-03-08",
    region: "US",
    type: "Rural Access",
    stage: "Drafting",
    owner: "Priya",
    funding: 22000,
    fit: 4,
    focus: "Rural student support with local partner approvals",
    link: "https://example.org/momentum",
  },
];
